### PR TITLE
Added estimated original time

### PR DESCRIPTION
**Pull request by ollan**
-Added estimated original time
-Added parent info to example SCRUM card
-Replaced tabs with whitespaces

### CODE REVIEW

**Comment by ollan** [comment]
Please accept my push request.

**Comment by Chariyski** [comment]
Hi @ollan,

I am unable to merge your pull request, due to un-fetched changes from your side.
Please resolve the conflicts, as descried in the box below.

Best regards

**Comment by ollan** [comment]
I'm new in GIT and GitHub. The box below says:

"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests."

Please explain and I will do my best make it mergable.

**Comment by Chariyski** [comment]
Hi @ollan, 

when you go to your repo ( https://github.com/ollan/JIRA-Cards-for-Task-Board ), you will see a message "This branch is 3 commits ahead, 2 commits behind Chariyski:master.". AS your repo is 2 commits behind mine, you need to fetch those two commits. [Here](https://help.github.com/articles/syncing-a-fork/) you can read more about it.

**Comment by ollan** [comment]
OK. Hopefully I did get it right.

**Comment by Chariyski** [comment]
Yes you did :D

**Comment by Chariyski** [comment]
I've publish v2.1.0 with some changes from my side.
You can check them [here](https://github.com/Chariyski/JIRA-Cards-for-Task-Board/commit/b5bc75d5bde689b5f9768c5d5e18579ecc6aff66)

**Pull request merged**
